# Gradle
org.gradle.jvmargs=-Xmx4096M
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.workers.max=4

# Kotlin
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.binary.memoryModel=experimental

# Android
android.useAndroidX=true
android.enableJetifier=false
android.disableAutomaticComponentCreation=true

# KSP
ksp.incremental=true

# Compose
compose.compiler.reflection=false
compose.ios.resources.sync=false
